version: '3.6'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    network_mode: "bridge"
  yellow-labs:
    image: jguyomard/yellowlabtools
    container_name: yellowlabtools
    ports:
      - "8383:8383"
    network_mode: "bridge"

