version: '3.6'
volumes:
  grafana-storage:
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
  yellow-labs:
    image: jguyomard/yellowlabtools
    container_name: yellowlabtools
    ports:
      - "8383:8383"
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  elasticsearch:
    image: elasticsearch
  kibana:
    image: kibana
    ports:
      - 5601:5601