---
version: '3.6'
volumes:
  grafana-storage:
  #mysql-storage: 
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports: ['3000:3000']
    volumes:
      - 'grafana-storage:/var/lib/grafana'
    network_mode: 'bridge'
  yellow-labs:
    image: jguyomard/yellowlabtools
    container_name: yellowlabtools
    ports: ['8383:8383']
    network_mode: 'bridge'
  db:
    image: mysql:5.7
    container_name: mysql
    ports: ['3306:3306']
    volumes:
      - '/opt/mysql/data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'yellowlab'
    network_mode: 'bridge'
  adminer:
    image: adminer
    container_name: adminer_mysql
    restart: always
    ports: ['8080:8080']
    network_mode: 'bridge'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    container_name: elasticsearch
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1']
    ports: ['9200:9200']
    network_mode: 'bridge'
  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    container_name: kibana
    ports: ['5601:5601']
    depends_on: ['elasticsearch']
    network_mode: 'bridge'
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports: ['9000:9000']
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/opt/portainer/data:/data'
    restart: unless-stopped
    network_mode: 'bridge'
  sonar:
    image: sonarqube:latest
    container_name: sonarqube
    ports: ['9100:9000']
    network_mode: 'bridge'